// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWatcher.Core.Data;

#nullable disable

namespace MovieWatcher.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421114339_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("MediaItemPlatformItem", b =>
                {
                    b.Property<Guid>("MediaItemsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlatformsId")
                        .HasColumnType("TEXT");

                    b.HasKey("MediaItemsId", "PlatformsId");

                    b.HasIndex("PlatformsId");

                    b.ToTable("MediaItemPlatformItem");
                });

            modelBuilder.Entity("MovieWatcher.Core.Entities.EpisodeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWatched")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeasonItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeasonItemId");

                    b.ToTable("Episodes");
                });

            modelBuilder.Entity("MovieWatcher.Core.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CsfdUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MediaItems");

                    b.HasDiscriminator<string>("ItemType").HasValue("MediaItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MovieWatcher.Core.Entities.PlatformItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("MovieWatcher.Core.Entities.SeasonItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SeriesItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SeriesItemId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("MovieWatcher.Core.Entities.MovieItem", b =>
                {
                    b.HasBaseType("MovieWatcher.Core.Entities.MediaItem");

                    b.HasDiscriminator().HasValue("Movie");
                });

            modelBuilder.Entity("MovieWatcher.Core.Entities.SeriesItem", b =>
                {
                    b.HasBaseType("MovieWatcher.Core.Entities.MediaItem");

                    b.HasDiscriminator().HasValue("Series");
                });

            modelBuilder.Entity("MediaItemPlatformItem", b =>
                {
                    b.HasOne("MovieWatcher.Core.Entities.MediaItem", null)
                        .WithMany()
                        .HasForeignKey("MediaItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieWatcher.Core.Entities.PlatformItem", null)
                        .WithMany()
                        .HasForeignKey("PlatformsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieWatcher.Core.Entities.EpisodeItem", b =>
                {
                    b.HasOne("MovieWatcher.Core.Entities.SeasonItem", "Season")
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MovieWatcher.Core.Entities.SeasonItem", b =>
                {
                    b.HasOne("MovieWatcher.Core.Entities.SeriesItem", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MovieWatcher.Core.Entities.SeasonItem", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("MovieWatcher.Core.Entities.SeriesItem", b =>
                {
                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
